name: CI

on:
  push:
    branches: [master, develop]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ⚙️ Node & pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 10
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm turbo lint

      - name: Unit tests
        run: pnpm turbo test

      - name: Build
        run: pnpm turbo build

  terraform-plan:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Init & Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd infra
          terraform init -backend-config="bucket=sshr-tf-state"
          terraform plan -out=plan.tfplan
      # TODO: upload plan & logs to S3 (compliance evidence)
